In [2]:
'''
Practicing SVM for spam classification
March 25, 2024
'''

'\nPracticing SVM for spam classification\nMarch 25, 2024\n'

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
email_train_df = pd.read_csv('Data/train-1.csv')
email_train_df.shape

(4459, 1365)

In [5]:
email_test_df = pd.read_csv('Data/test-1.csv')
email_test_df.shape

(1115, 1365)

In [6]:
combined_df = pd.concat([email_train_df, email_test_df])
combined_df

...  u  call  's  2  get  go  'm  ur  n't  ...  norm150p/ton  instead  \
0       2  0     0   0  0    0   1   0   0    0  ...             0        0   
1       2  1     0   0  0    0   0   0   0    0  ...             0        0   
2       0  0     0   2  1    0   0   0   0    0  ...             0        0   
3       0  0     0   0  0    0   0   0   0    1  ...             0        0   
4       0  0     0   2  0    0   0   0   0    0  ...             0        0   
...   ... ..   ...  .. ..  ...  ..  ..  ..  ...  ...           ...      ...   
1110    0  0     0   0  0    0   0   0   0    0  ...             0        0   
1111    0  0     0   1  0    0   0   2   0    0  ...             0        0   
1112    0  0     0   0  2    0   2   0   0    0  ...             0        0   
1113    0  1     1   0  2    0   0   0   0    0  ...             0        0   
1114    1  0     0   0  0    0   0   0   0    0  ...             0        0   

      sim  tyler  cri  hunni  cross  slave  whether  label  
0       0      0    0      0      0      0        0      0  
1       0      0    0      0      0      0        0      0  
2       0      0    0      0      0      0        0      1  
3       0      0    0      0      0      0        0      0  
4       0      0    0      0      0      0        0      1  
...   ...    ...  ...    ...    ...    ...      ...    ...  
1110    0      0    0      0      0      0        0      1  
1111    0      0    0      0      0      0        0      0  
1112    0      0    0      0      0      0        0      0  
1113    0      0    0      0      0      0        0      1  
1114    0      0    0      0      0      0        0      0  

[5574 rows x 1365 columns]

In [7]:
''' Select columns'''
# Assign the independent variable
feature_df = combined_df.iloc[:, :-1]
X = np.asarray(feature_df)
print(X)

y = np.asarray(combined_df['label'])
print(y)

[[2 0 0 ... 0 0 0]
 [2 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[0 0 1 ... 0 1 0]


In [8]:
''' 
Divide the data into training and test data
if we didn't have the test-1.csv data, we would split the current dataset into train/test

from sklearn.model_select import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
'''

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

X_train.shape
y_train.shape

X_test.shape
y_test.shape

(1115,)

In [9]:
''' Use the SVM model '''
from sklearn import svm

classifier = svm.SVC(kernel='linear', gamma='auto', C=2)

# fit the data
classifier.fit(X_train, y_train)

# Output is 1D
y_predict = classifier.predict(X_test)

In [10]:
''' Evaluate the results '''
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       962
           1       0.95      0.89      0.92       153

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [14]:
''' Comparison with Logistic Regression '''
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(C=1e5)
logreg.fit(X_train, y_train)

y_predict = logreg.predict(X_test)

In [15]:
''' Evaluate the results '''
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       962
           1       0.95      0.90      0.93       153

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

